# Generated by Django 5.0 on 2023-12-19 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_followerscount_likepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profileimage',
            new_name='profileimg',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
